spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cooperativa_votacao}
    username: ${SPRING_DATASOURCE_USERNAME:usuario}
    password: ${SPRING_DATASOURCE_PASSWORD:senha}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region_prefix: jcache
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
        javax:
          cache:
            missing_cache_strategy: create
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform

    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 600000
    jcache:
      config: classpath:ehcache.xml
  data:
    redis:
      host: redis
      port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: NON_NULL

logging:
  level:
    root: INFO
    com.example.cooperativa: INFO
    org.ehcache: INFO

cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowedMethods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}

cpf:
  validator:
    url: ${CPF_VALIDATOR_URL:http://validator:8081/users/{cpf}} #https://user-info.herokuapp.com/users/{cpf}

scheduler:
  updateRate: ${SCHEDULER_UPDATE_RATE:60000}

resttemplate:
  connect:
    timeout: ${RESTTEMPLATE_CONNECT_TIMEOUT:2000}
  read:
    timeout: ${RESTTEMPLATE_READ_TIMEOUT:2000}